Create operator-tools module to get token reader-secret
banzaicloud/operator-tools pull request #116
Opened 2022-12-16 16:21 UTC by shanchunyang0919

TODO: 
Regression/smoke tests

2022-12-16 22:56 UTC, Laci21 approved these changes
lgtm (took a quick glance only)

2022-12-19 21:50 UTC, nishantapatil3 approved these changes
lgtm!

2022-12-20 11:47 UTC, waynz0r requested changes

2022-12-20 11:47 UTC, waynz0r commented on pkg/secret/secretgetter.go
> +func NewReaderSecretGetter(opt *ReaderSecretGetterOption) (SecretGetter, error) {
```suggestion
func NewReaderSecretGetter(client client.Client) (SecretGetter, error) {
```

2022-12-20 11:47 UTC, waynz0r commented on pkg/secret/secretgetter.go
> +	Get() (*K8sSecret, error)
```suggestion
	Get(objectKey client.ObjectKey) (K8sSecret, error)
```

2022-12-20 11:47 UTC, waynz0r commented on pkg/secret/secretgetter.go
> +type K8sSecret struct {
```suggestion
type K8sSecret interface {
        GetToken() []byte
        GetCACert() []byte
}

type k8sSecret struct {
```

2022-12-20 11:47 UTC, waynz0r commented on pkg/secret/secretgetter.go
> +func (r *readerSecretGetter) Get() (*K8sSecret, error) {
```suggestion
func (r *readerSecretGetter) Get(objectKey client.ObjectKey) (K8sSecret, error) {
```

2022-12-20 11:47 UTC, waynz0r commented on pkg/secret/secretgetter.go
> +var defaultBackoff = wait.Backoff{
make this overridable

2022-12-20 20:15 UTC, shanchunyang0919 commented
Thanks for reviewing @waynz0r. I have pushed some new fixes.

2022-12-21 15:08 UTC, waynz0r requested changes

2022-12-21 15:08 UTC, waynz0r commented on pkg/secret/secretgetter.go
> +	saRef := types.NamespacedName{
saObjectKey can be used directly as it is types.NamespacedName already

2022-12-21 15:08 UTC, waynz0r commented on pkg/secret/secretgetter.go
> +		backoffWaitSecret := wait.Backoff{
still not overridable by the user, it can be moved to an overridable option using functional option pattern

2023-01-04 18:08 UTC, waynz0r approved these changes

2023-01-04 18:09 UTC, shanchunyang0919 commented
Thanks for approval and reviews @waynz0r @Laci21 @nishantapatil3

2023-01-04 18:09 UTC, merged