helm reconciler enhancements
banzaicloud/operator-tools pull request #85
Opened 2021-11-03 18:41 UTC by waynz0r

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | 
| License         | Apache 2.0

### What's in this PR?

- fix helm reconciler inventory configmap name
- fix recreate error message substring handling
- add support to have custom desired state for resources in helm reconciler based on GVK and object key
- export GetResourceBuilders in helm reconciler
- add NewHelmReconcilerWith constructor to helm reconciler which support options
- add helm reconciler option to override native and generic reconciler options
- add helm reconciler option to specify whether to manage the namespace object

2021-11-04 14:24 UTC, pepov approved these changes

2021-11-05 08:59 UTC, stoader commented on pkg/helm/templatereconciler/reconciler.go
> +	DesiredStateOverrides map[reconciler.ObjectKeyWithGVK]reconciler.DesiredState
Instead of allowing desired state override wouldn't be more flexible if a modifier func could be specified by user? That would allow greater flexibility regarding overriding the desired state for objects.

2021-11-05 09:44 UTC, stoader requested changes

2021-11-05 09:44 UTC, stoader commented on pkg/helm/templatereconciler/reconciler.go
> +			resourceBuilders = append(resourceBuilders, chartResourceBuilders...)
Move this just before `if doInventory`

2021-11-05 15:24 UTC, stoader approved these changes

2021-11-05 15:25 UTC, baluchicken approved these changes

2021-11-06 09:45 UTC, merged