Bump dependencies to support Kubernetes 1.23
banzaicloud/operator-tools pull request #96
Opened 2022-01-17 12:44 UTC by chrisgacsal

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| API breaks?     | yes
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
Update dependencies to support Kubernetes 1.23. 

This also introduces a breaking change related to `logging.logger` which can no longer be used as implementation of `logr.Logger` interface due to the changes introduced in `go-logr/logr` v1.0. In order to keep the original functionality of the `logging` package, the `logr.Logger` is replaced with custom `logging.Logger` type.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

2022-01-17 13:44 UTC, baluchicken approved these changes
LGTM thx @chrisgacsal

2022-01-18 07:35 UTC, pepov approved these changes

2022-01-18 07:58 UTC, baluchicken approved these changes

2022-01-18 10:23 UTC, hi-im-aren commented on pkg/logger/logsink.go
> +// Enabled  implements logr.LogSink interface
```suggestion
// Enabled implements logr.LogSink interface
```

2022-01-18 10:25 UTC, hi-im-aren commented on pkg/logger/logsink.go
> +// Enabled  implements logr.LogSink interface
<img src="https://media2.giphy.com/media/elHDhmQ4GDHIUAWPNs/giphy.gif"/>

2022-01-18 10:25 UTC, hi-im-aren approved these changes

2022-01-18 11:44 UTC, waynz0r approved these changes

2022-01-18 12:39 UTC, pepov requested changes

2022-01-18 12:39 UTC, pepov commented on pkg/logger/logsink.go
> +	l.values = append(l.values, keysAndValues)
```suggestion
	l.values = append(l.values, keysAndValues...)
```

2022-01-18 12:43 UTC, chrisgacsal commented on pkg/logger/logsink.go
> +	l.values = append(l.values, keysAndValues)
Nice catch! Ty

2022-01-18 14:45 UTC, merged